### PR TITLE
Fix phase plane noise slider config (TVB-3026)

### PR DESCRIPTION
**Pull request by JulieCB**
Hi,

Fixation of a bug for noise usage.

### CODE REVIEW

**Comment by JulieCB** [comment]
Hi Paula,

I have a bug when using stochastic scheme (Euler or Heun). I am using a jupyter notebook to visualize the results.
The error I get it's this one:
`AttributeError: 'float' object has no attribute 'rint'` indicating line 404 `self.noise_slider = widgets.Slider(sax, "Log Noise", -9.0, 1.0, valinit=self.integrator.noise.nsig)`

Hope that helps you!

I also have a short question: why using "Log Noise"?

**Comment by maedoc** [comment]
Log noise is appropriate because the noise scaling cannot be negative, and the interesting tuning is on a logarithmic scale which allows changing order of magnitude more easily than linear.

**Comment by VinczeRobert** [comment]
I tried to reproduce the error but I wasn't able to. It seems like this add_noise_slider method is called from the show method of the PhasePlanInteractive class. I ran the cells from tutorial_s3_exploring_a_model notebook cause I saw that the show method is called there, but everything ran smoothly.

Could you maybe copy-paste here that code that you ran when encountering the problem?

**Comment by JulieCB** [comment]
The problem appears when using small noise values below 1.


---
Best regards,

Julie Courtiol





Le jeu. 2 sept. 2021 à 15:23, Vincze Robert ***@***.***> a
écrit :

**Comment by maedoc** [comment]
@JulieCB reply by email doesn't post the attachment, please open GitHub and post it

**Comment by JulieCB** [comment]
Using tutorial_s3_exploring_a_model.ipynb:

in the Stochastic Integration section, if we modify the noise strength and set it to a value below 1 like here: 0.01

nsigma = np.array([0.01,])           
hiss = noise.Additive(nsig=nsigma)   
heunstoint = integrators.HeunStochastic(dt=dt, noise=hiss)  

you should get an error in the function add_noise_slider: 'float' object has no attribute 'rint'

**Comment by maedoc** [comment]
Ok, this allows the UI to show up, but the noise slider doesn't work, and the same error message shows up in the console when trying to change the noise level. 

Additionally, the PPI doesn't update trajectories when moving the slider.

**Comment by maedoc** [comment]
@JulieCB any updates?

**Comment by liadomide** [comment]
I think the better fix here is:
```
        self.noise_slider = widgets.Slider(sax, "Log Noise", -9.0, 1.0,
                                           valinit=self.integrator.noise.nsig[0])
```
because params `valmin, valmax, valinit` all expect single float values, and the previous `valinit=self.integrator.noise.nsig` seems to be the culprit.

Would you agree that i close this PR, make this change in a tvb-root branch, then we merge ?

**Pull request closed without merging**
