### PR TITLE
TVB-2651 Review BrainActivityViewer

### PR DESCRIPTION
**Pull request by liadomide**
We seem to have a broken functionality in TSRegion BrainActivity viewer (after recent fix for TSSurface same viewer).
Also some slow or complex code can be observed in these parts.

### CODE REVIEW

**Comment by VinczeRobert** [comment]
Firstly, I apologize for the problems that I created.

Secondly, the only thing that I changed was adding that question mark instead of the slash, because the parameters were not sent correctly and I was getting this error: Traceback (most recent call last):
  File "C:\Users\Robert.Vincze\Desktop\TVB_ORIG\tvb-root\framework_tvb\tvb\interfaces\web\controllers\decorators.py", line 147, in deco
    return func(*a, **b)
  File "C:\Users\Robert.Vincze\Desktop\TVB_ORIG\tvb-root\framework_tvb\tvb\interfaces\web\controllers\decorators.py", line 96, in deco
    result = func(*a, **b)
  File "C:\Users\Robert.Vincze\Desktop\TVB_ORIG\tvb-root\framework_tvb\tvb\interfaces\web\controllers\decorators.py", line 193, in deco
    return func(*a, **b)
  File "C:\Users\Robert.Vincze\Desktop\TVB_ORIG\tvb-root\framework_tvb\tvb\interfaces\web\controllers\flow_controller.py", line 610, in read_from_h5_file
    result = result()
TypeError: read_channels_page() missing 2 required positional arguments: 'from_idx' and 'to_idx'

I checked the tests and I also tested the visualizers manually, now I believe everything is fine.

**Comment by liadomide** [comment]
No need to apologize.
I should not have merged so soon.

I still think the current form in this branch has problems with some viewers (not actually tested, but I can  anticipate from the code). Maybe dual viewer, or TSEEG...

**Comment by liadomide** [comment]
It looks ok to me, too.

The only thing I found broken is the usage of `ts_h5.get_grouped_space_labels` and especially `ts_h5.get_space_labels`. That part is deprecated, and should be replaced with `ABCSpaceDisplayer._get_grouped_space_labels` and `ABCSpaceDisplayer.get_space_labels`

**Comment by liadomide** [comment]
Unit and Manual Tests are ok in my local env. I will merge this.

**Pull request merged**
