### PR TITLE
Unified RateML

### PR DESCRIPTION
**Pull request by DeLaVlag**
Hello @maedoc and @sdiazpier. This PR is about unifying the CUDA and Python RateMLs and using an unmodified Pylems which can be installed as a dependency. The interface of RateML is expanded with 2 arguments: language for generation and user can enter a location in which generated models are stored. Also XSD validation for XML files is added. For the CUDA models now also a BOLD kernel is generated. The two collabs featuring TVB and CUDA model generation + simulation are added to TVB demos folder.

### CODE REVIEW

**Comment by maedoc** [comment]
PR is too long to scrape my eyes over by hand.  I will pull the branch and check the files modified lie entirely within the dsl/rateml package.  can you point me to the test suite please?

**Comment by DeLaVlag** [comment]
> PR is too long to scrape my eyes over by hand. I will pull the branch and check the files modified lie entirely within the dsl/rateml package. can you point me to the test suite please?

Tests on RateML are here: scientific_library/tvb/tests/library/simulator/models_test.py
I had to alter some files outside RateML to ensure correct testing and installation: 
scientific_library/Dockerfile 
scientific_library/MANIFEST.in
scientific_library/setup.py

**Comment by DeLaVlag** [comment]
> Also, I tried to start improving the notebook on using this:
> #241
> would you be able to update that PR or push an improved notebook here?

Yes I have now this notebook incorporating yours. It runs a rateml generated model on Jusuf or Juwels:
tvb_documentation/demos/RateML_CUDA_on_HPC.ipynb

**Comment by maedoc** [comment]
thanks for the updates. I will go through this next week.

**Comment by maedoc** [comment]
I started looking at this, trying to get it to run locally.  We have a new model to add, so I'll try this PR for that and come back soon.

**Comment by maedoc** [comment]
Moving away from a custom LEMS is a good thing I think, though I received the comment that instead of a spin off of LEMS it may be better to work with the LEMS authors to improve their DSL.  I don't have a preference, and it could be just as easy to use a diffeent concrete syntax for the DSL to stick with the notion of a rate-based model DSL.  Just a discussion item for later @sdiazpier 

I have tried to run this locally, and while the unit tests pass, I don't think they provide good coverage as a number of other issues 

- the default run config for CUDA tries to run incorrectly generated template (nvcc errors out on syntax problems)
- the montbrio model passes nvcc but generates a bunch of illegal access errors (equivalent of SIGSEGV for GPU)
- errors produced by PyCUDA don't seem to be handled but 
- unit tests don't cover CUDA at all in fact
- the generated kernels attempt to do temporal averaging for all state variables but the driver code only allocates for one

None of these are insurmountable, and the generated code & driver is close to correct, but I think a more meticulous testing process would be helpful.  Specifically, it could be helpful to split process into a frontend and a backend: a frontend consumes LEMS and generates a TVB intermediate representation (a `Simulator` object) and a backend consumes a `Simulator` and uses a CUDA device (via templating+driver) to return time series.  This would allow the unit tests to isolate issues with the frontend vs backend.  Testing the behavior of CUDA vs existing TVB would also be easier.

cc @i-Zaak

**Comment by maedoc** [comment]
Following up with my previous comment, I started with the Montbrio model and the Sigmoidal coupling function, building up templates from scratch.  In Python for now, but what I wish to emphasize is the granularity of the tests: we should be able to run a suite of unit tests to pin point immediately where the issue is.  Currently, we have at best integration tests which just tell us that overall the simulator doesn't work.

https://github.com/the-virtual-brain/tvb-root/commit/7637c70f38a099cdcdece2c6f2a74237a5ee9b45

There are just a few things required extending TVB's classes for models and coupling functions, such as a list of parameter names and strings with the expressions of the dfuns and coupling function expressions.  I think these are straightforward to fill in from the corresponding fields of the RateML parse tree, but as mentioned above achieve a sort of intermediate representation (IR) in the form of a TVB component that can then be rendered to a concrete form.

Mako looks flexible enough that a generic template (loop with update coupling, update nodes, update monitors) etc should be retargetable to CUDA, C, Python and so on, by delegating the bits of code generation to a module of Mako defs.  Ideally this is more maintainable long term than monolithic templates.

**Comment by maedoc** [comment]
Sorry for the problems with the CI runner.  It stopped working and I’m trying to fix it.  It should just work now, with nvcc and pycuda all set up, if you just use `runs-on: self-hosted`.

**Comment by maedoc** [comment]
All test passed locally, which is nice to see, though I had to change the model driver template to raise the min speed to 3.  Why was it set to 3e-3 ?  This makes the history buffer very large. 

I would later like to un-template the driver, since, when shipping TVB, we can't have TVB regenerating its source code where it's installed, but this can be resolved later.

I can resolve the conflicting files or you want to do it?

**Comment by DeLaVlag** [comment]
Please go ahead and resolve conflicts. I had set the min speed to 3 ms as you suggested. Its already at ms scale then?

**Comment by maedoc** [comment]
> e min speed to 3 ms as you suggested. Its already at ms scale then?
TVB interprets speed argument in m/s or mm/ms, tract lengths in mm, and dt in ms, so the tract length is divided by dt, then divided by speed such that all units cancel out, leaving just the number of steps to delay.

**Comment by maedoc** [comment]
I see 4 failing tests from pytest:
```
FAILED rateml_test.py::TestRateML::test_time_serie - assert False
FAILED rateml_test.py::TestRateML::test_compile_cuda_models[kuramoto] - pycuda.driver.CompileError: nvcc compilation of /tmp/tmp_jhn03xj/kernel.cu failed
FAILED rateml_test.py::TestRateML::test_compile_cuda_models[montbrio] - pycuda.driver.CompileError: nvcc compilation of /tmp/tmpgocox3re/kernel.cu failed
FAILED rateml_test.py::TestRateML::test_eval_model_str - tvb.basic.neotraits.ex.TraitValueError: value[0]=='x1' must be one of ('x1 ** x2', 'x2')
```
From the montbrio test for instance, the traceback ends with
```
E           pycuda.driver.CompileError: nvcc compilation of /tmp/tmp_jhn03xj/kernel.cu failed
E           [command: nvcc --cubin -arch sm_61 -I/opt/conda/lib/python3.7/site-packages/pycuda/cuda kernel.cu]
E           [stderr:
E           kernel.cu(72): error: expected an expression
E           
E           kernel.cu(73): error: expected an expression
E           
E           kernel.cu(106): error: identifier "V" is undefined
E           
E           kernel.cu(81): warning: variable "wij" was declared but never referenced
E           
E           3 errors detected in the compilation of "kernel.cu".
E           ]

/opt/conda/lib/python3.7/site-packages/pycuda/compiler.py:155: CompileError
```
I don't have access to the CI machine I set up previously (but I'll check it out tomorrow). I assume you were running tests locally before pushing commits, so if you can share you setup that would help.

**Comment by maedoc** [comment]
Btw I will push my changes to the branch here: https://github.com/the-virtual-brain/tvb-root/tree/urateml and when things look a little better, I'll just ask you to rebase this PR on that branch.

**Comment by maedoc** [comment]
I just noticed I see another branch here: https://github.com/the-virtual-brain/tvb-root/tree/unified-rateml

Which one are you pushing to?  It would be simpler for us to have this PR based on this branch in the repo so multiple people can push, if you feel like doing the switch.

**Comment by DeLaVlag** [comment]
I was using the latter for the GPU runner experiment. Lets use it (https://github.com/the-virtual-brain/tvb-root/tree/unified-rateml) for our changes.

**Comment by maedoc** [comment]
OK then I will poke the CI machine and get the runner up again.

**Comment by DeLaVlag** [comment]
Ok. I will find a fix for these errors. The errors should be runner independent though

**Comment by maedoc** [comment]
I have the machine up, and I'll try to get the builds running again

**Comment by maedoc** [comment]
thanks, I still see two failures running locally
```
FAILED tvb/tests/library/simulator/rateml_test.py::TestRateML::test_check_parameters - assert (1 == 2
FAILED tvb/tests/library/simulator/rateml_test.py::TestRateML::test_time_serie - assert False
```
do these pass for you?

**Comment by DeLaVlag** [comment]
they pass for me locally yes. have you modified anything regarding the driver generation? these test rely on RateML being run and setting up the driver.

**Comment by maedoc** [comment]
after doing some merge testing and fixing the `.github/workflows/tests.yml` and `Dockerfile` conflicts, there are just a few other files I need to review 
- [ ]`MANIFEST.in`
- [ ] `setup.py`
- [ ] `tvb/simulator/models/epileptor.py`
- [ ] `...oscillator.py`
- [ ] `tvb/tests/library/simulator/models_test.py`
the rest of the changes are isolated to the rateML folders or are template-related changes.

**Comment by maedoc** [comment]
The epileptor and oscillator module changes are just whitespace.  I prefer not to commit changes like that as it dirties the git blame output, but nothing to worry about.

**Comment by maedoc** [comment]
I am OK with this PR (or rather the changes in the unified-rateml branch), so tomorrow I'll open PR with all the conflicts cleaned up for merging.  This doesn't change the commit authors just makes it easier to merge.

**Comment by maedoc** [comment]
I'm closing this PR for #468 which is fixing merge conflicts & CI runs.

**Pull request closed without merging**
