### PR TITLE
Change test for Wilson cowan

### PR DESCRIPTION
**Pull request by lionelkusch**
Fix error from the pull request : https://github.com/the-virtual-brain/tvb-root/pull/365

### CODE REVIEW

**Comment by maedoc** [comment]
comment in the docstring plz

**Comment by lionelkusch** [comment]
What do you mean?
The table 1 contains the values for the Deco paper and the initial values of TVB paper.
Do you think the following sentence is not enough explicit ? l162 : "The parameters in Table 1 reproduce Figure A1 in  [D_2011]_"

**Comment by maedoc** [comment]
ah sorry I didn't see a change here so I thought it wasn't there.

**Comment by lionelkusch** [comment]
@maedoc you can merge it.

**Comment by maedoc** [comment]
just to avoid previous error, I'll wait until the tests pass..

**Pull request merged**
