### PR TITLE
TVB-2834 Import tumor data from ebrains dataset

### PR DESCRIPTION
**Pull request by bvalean**
Import TVB Tumor Data demos

### CODE REVIEW

**Review by liadomide — APPROVED** [review]
As far as i can judge this looks ok

**Comment by popaula937** [comment]
Should we import also the surface and region mapping from tvb_data/berlinSubjects from within the script?

**Comment by popaula937** [comment]
Maybe we should not introduce in the command API the possibility to receive dictionaries that have to be transformed to view_models. I believe preparing a dict (ensuring all attributes are written correctly as strings) is not easier than preparing directly the view_model object.

**Comment by bvalean** [comment]
> Should we import also the surface and region mapping from tvb_data/berlinSubjects from within the script?

Did it

**Review by popaula937 — APPROVED** [review]

**Comment by popaula937** [comment]
PR checks are failed because Zenodo is down.

**Pull request merged**
