### PR TITLE
Adding monitor for calcium signal

### PR DESCRIPTION
**Pull request by nuuria8**
Convert firing rates into calcium signal (to compare with wide field signals)

### CODE REVIEW

**Comment by maedoc** [comment]
thanks for your contribution!

Could you additionally provide

- [ ] one or more citations for the equations
- [ ] a demo script or Jupyter notebook to the [demos folder](https://github.com/the-virtual-brain/tvb-root/tree/master/tvb_documentation/demos)
- [ ] a unit test which checks that the monitor doesn't produce errors when used

**Comment by nuuria8** [comment]
Hello, can I do something to resolve the conflicts above?

**Comment by nuuria8** [comment]
Hello, can I do something to resolve the conflicts above?

**Comment by nuuria8** [comment]
Hello, can I do something to resolve these conflicts?

**Comment by i-Zaak** [comment]
Dear @nuuria8 I have resolved the conflict and moved the pull request to a local branch: #523 This way we also get the CI run the tests.

**Comment by maedoc** [comment]
@nuuria8 as I commented in #523, the amount of stuff in the PR is too large.  The monitor, a small test and demo would be more appropriate.  The full use case that you've worked out can be considered separately, but perhaps because of the code size, it would be better suited as an individual repository, unless you are willingly to integrate more of the pieces with TVB.

**Comment by liadomide** [comment]
I close this, as the work has been continued in #523

**Pull request closed without merging**
