### PR TITLE
Add CUDA support for the DSL

### PR DESCRIPTION
**Pull request by maedoc**
From @DeLaVlag and @sdiazpier, developed in the TVB-HPC repository, extends DSL for generating full simulation loops for GPU-based parameter sweeps with the DSL.

@DeLaVlag if you want to push some commits here, please fork this repo, checkout this branch, push the branch to your fork and we can redo the PR from your copy. 

small checklist prior to merge

- [ ] get a review
- [ ] notebook to demo running one of the generated kernels

### CODE REVIEW

**Comment by maedoc** [comment]
I'm not yet sure how we will handle CUDA dependencies.  But, for the moment, on a system with CUDA 10 set up, I have done
```
conda create -n tvb-dsl-cuda python=3 numpy numexpr matplotlib numba
pip install tvb-data pycuda
cd scientific_library && python setup.py develop
cd tvb/dsl_cuda/example
python cuda_setup.py --model Kuramoto -c 128 -s 64
```
and it runs successfully.

**Comment by maedoc** [comment]
Let's restrict this PR to just the DSL to CUDA code gen + a notebook which demos it and worry about messy deployment stuff later (since CUDA deployment is OK but not easy especially for CI).

**Comment by maedoc** [comment]
@i-Zaak don't worry about reviewing the whole thing, just poke around the templates a bit and see if there are any red flags plz

**Comment by i-Zaak** [comment]
Looks good to me. Looking forward to the benchmarks :+1:

**Review by i-Zaak — APPROVED** [review]

**Pull request merged**
