### PR TITLE
TVB-2791. Fix disk usage computation test

### PR DESCRIPTION
**Pull request by popaula937**
Exclude view model H5 files from disk usage computation

### CODE REVIEW

**Comment by liadomide** [comment]
Wouldn't be correct to include all files in the project size, thus not exclude the VMs from the actual size in test, but consider them also for the Project disk size computed field?

**Comment by popaula937** [comment]
> Wouldn't be correct to include all files in the project size, thus not exclude the VMs from the actual size in test, but consider them also for the Project disk size computed field?

I agree but I think that would be a separate task since currently, we determine the project size by adding all Datatype.disk_size values from DB and we do not keep any information about the view_model.h5 size in DB.

**Comment by liadomide** [comment]
> > Wouldn't be correct to include all files in the project size, thus not exclude the VMs from the actual size in test, but consider them also for the Project disk size computed field?
> 
> I agree but I think that would be a separate task since currently, we determine the project size by adding all Datatype.disk_size values from DB and we do not keep any information about the view_model.h5 size in DB.

I think a task already exists in Jira .... 
Could we put disk size of the VM on the Operation table in DB?

**Comment by popaula937** [comment]
Will be fixed by task [TVB-2767](https://req.thevirtualbrain.org/browse/TVB-2767)

**Pull request closed without merging**
