### PR TITLE
initial startup speed-up

### PR DESCRIPTION
**Pull request by maedoc**
When just trying to write unit tests and run them, the startup time of
the library is slow enough to get distracted (8.2 s on i5 SSD Mac).
Looking at the extensive log output, I saw enough delay between warnings
of different models to realize that importing all models is causing this
delay.

I then commented the imports of tvb.simulator.models.__init__ and saw
startup time drop to 0.5 s.  I would guess that this speed drop is due
to the gufunc or neotraits class registration, not yet sure which.

The current fix is breaking code such as

     from tvb.simulator.models import Linear

so it would be useful to resolve the underlying problem *or* implement
a lazy loading approach, since, at runtime, only one model is usually
in use; loading all is excessive.

@mihandrei @liadomide ideas?

### CODE REVIEW

**Comment by maedoc** [comment]
The workaround implemented works but requires some familiarity with Python's modules to understand.  The speed up is as reported before since the model modules are lazily loaded.

**Comment by liadomide** [comment]
I have a small suggestion: to leave just yourself as author on this file, or to remove authors entirely from here. Now, I think it is an incomplete list of authors for tvb models

**Comment by maedoc** [comment]
@liadomide why is this assigned after merge?

**Comment by liadomide** [comment]
I was playing with GitHub GUI.
I wanted to have a filled top view of the PRs and someone assigned to each (for the closed ones the people involved).
.... but mainly playing with the GUI. Sorry for the spam :-)

**Comment by maedoc** [comment]
no problem play away, just wanted to make sure I'm not missing anything!

**Pull request merged**
