### PR TITLE
Done profilling

### PR DESCRIPTION
**Pull request by Raghibshams456**
Profiling of benchmark.py...need some guidance what to do after this..
Screenshot from 2021-04-08 18-25-52
Screenshot from 2021-04-08 18-25-45

### CODE REVIEW

**Comment by maedoc** [comment]
I would suggest using cProfile instead of line profiler, then sort by time and compare between profiles.  There should be some clear function calls standing out in the command profile not present in the library profile.

**Comment by Raghibshams456** [comment]
@maedoc please have a look...

**Comment by maedoc** [comment]
I think it might make more sense to do the profiling within the simulator, because the benchmark you have here only measures the performance in command profile, not library profile.  Also I would guess that the simulation which is a submitted operation does not run in the same process as the script, so the profiler won't catch it.

**Comment by Raghibshams456** [comment]
can you suggest on which part of code should I focus if I want to improve 

   1. Simulation wizard
   2. H5 files writing
    3..loading for visualizers from files
actually this is project of gsoc 2021 and I want to work on this..

**Comment by maedoc** [comment]
Ah I see the goal is a bit wider.  If you want to profile across the web server, [Yappi](https://pypi.org/project/yappi/) might be a good choice.  But yes, for profiling the simulator itself, you need would want to use cProfile in the run method.

**Comment by Raghibshams456** [comment]
@maedoc  can u guide me I writing proposal of that project "benchmarking and otimising tvb areas"..any hints
??

**Comment by liadomide** [comment]
@Raghibshams456 I think this is a good start.
I suggest: 
- you create your own branch, maybe directly from tvb-root master branch (or rebased to it), but still containing the changes done to fix `benchmark.py` from the current branch
- for catching simulator execution stack (as pointed by Maedoc above), try to change `SimulatorAdapter.launch_mode` to `AdapterLaunchModeEnum.SYNC_SAME_MEM`
- then indeed, we will need to go towards profiling cherrypy server. Yappi would be a good choice, but also something like Selenium would be a good tool, from my point of view, to identify slow web pages. Here, it is up to you to propose a good solution, as part of your application

**Pull request closed without merging**
