### PR TITLE
Modification Wilson Cowan for reproducibility

### PR DESCRIPTION
**Pull request by lionelkusch**
Hi all,
I reopen a pull request on this topic. I am sorry, I didn't have the time to finish the last pull request : https://github.com/the-virtual-brain/tvb-library/pull/74 .

This pull request is to modification of the model Wilson Cowan for include the shift of the sigmoid present in the original model but not implemented.
I included a jupyter-notebook for reproduce the figure 4 in Wilson Cowan and the figrue A1 in  Daffertshofer and van Wijk (2011)

### CODE REVIEW

**Comment by lionelkusch** [comment]
@maedoc some news ?

**Comment by maedoc** [comment]
There's a test failure here https://github.com/the-virtual-brain/tvb-root/runs/3489568246?check_suite_focus=true, could you take a look?

We didn't see it because this PR branches from before that CI script was set up.

**Comment by lionelkusch** [comment]
The error came from that I change the default value for the Wilson Cowan paper and not the Deco paper.
model_test.py : self._test_steady_state(model, numpy.r_[0.474, 0.256])

Can I change the value of the test? or Should I change the default parameters?

**Comment by maedoc** [comment]
Please change the value of the test, and add a note to the docstring that the Deco paper uses a different value.

**Comment by maedoc** [comment]
You could just push another commit here and we merge that as well.

**Comment by lionelkusch** [comment]
Sorry, I can't push here a commit. I need to create a new pull request. (https://github.com/the-virtual-brain/tvb-root/pull/466)

The Docstring already has a note about it.

**Pull request merged**
