### PR TITLE
HBP-87. Extracted changes related to history bound/clamp and added tests

### PR DESCRIPTION
**Pull request by popaula937**
Code extracted from PR #37

### CODE REVIEW

**Comment by popaula937** [comment]
@dionperd I have separated the bound_and_clamp of history in this PR in order to add some tests. 
Could you review these and let me know what is your opinion?

**Review by dionperd — APPROVED** [review]
I obviously agree with extracting those changes.

Tests seem OK.

**Comment by liadomide** [comment]
@maedoc Do you think this is generic enough to be merged into tvb-library simulator ?
I think this is developed with the co-simulator models in mind (as the code was extracted from there) but can it be merged independently, as a good feature for the simulator itself?
It seem to also be continuing/completing a previous added feature by @dionperd.

PS: not urgent

**Review by liadomide — APPROVED** [review]

**Review by maedoc — APPROVED** [review]
This is a good idea

**Pull request merged**
