### PR TITLE
Transposing Allen connectome  for TVB connectivity

### PR DESCRIPTION
**Pull request by dionperd**
I modified the allen_creator.py adaptor.

However, I cannot regenerate the connectivity.h5 file that is used in the notebooks.

Please help!

### CODE REVIEW

**Comment by maedoc** [comment]
Unfortunately, it is unlikely that you would be able to reproduce the results.  Allen frequently updates their ontology and data, and terms of use do not allow us to have a versioned cache, if I recall correctly.  This means that the matrix that's created will vary in time.

**Comment by dionperd** [comment]
> Unfortunately, it is unlikely that you would be able to reproduce the results. Allen frequently updates their ontology and data, and terms of use do not allow us to have a versioned cache, if I recall correctly. This means that the matrix that's created will vary in time.

I am not trying to reproduce results but to reproduce the connectivity that ships with TVB (mouse/allen_2mm/Connectivity.h5) and is loaded by the notebook simulate_for_mouse.ipynb in documentations/demos.
I cannot reproduce it because for some reason, when I list_projects() in interacting_with_Allen.ipynb, I don't find any and the notebook doesn't run...

**Comment by maedoc** [comment]
> reproduce the connectivity that ships with TVB (mouse/allen_2mm/Connectivity.h5)

That's what I meant by reproduce.  Maybe their ontology has changed and now the creator doesn't work.  However, unlike the lack of transpose that you identified, this is not a bug with TVB: the underlying data source is changing over time, and the license for the data does not allow us to cache the source data, only our derived artifacts.  Furthermore, no one has had time to maintain this over the years.

Let's keep this PR simple: we have the transpose now, and we're done.

**Review by maedoc — APPROVED** [review]

**Comment by dionperd** [comment]
That's fine! The important thing is that whoever regenerated an Allen connectome will have correctly transposed now.
If someone can also regenerate the connectivity.h5 that ships with TVB even better!
I would prefer if I am not that person! :)

**Pull request merged**
