### PR TITLE
DSL related licences

### PR DESCRIPTION
**Pull request by liadomide**
I see Mako and NeuroML as new dependencies brought by the DSL. Something else?

These should be listed under accepted TVB dependencies.
For mako it was easy to identify the license. 
Could you point to what from NeuroML we should cite ?

### CODE REVIEW

**Comment by liadomide** [comment]
@DeLaVlag Could you pls help us with the dependencies licenses also?

**Comment by maedoc** [comment]
LEMS is the relevant repo (https://github.com/LEMS/pylems) and is [LGPL licensed](https://github.com/LEMS/pylems/blob/master/LICENSE.lesser)

**Comment by maedoc** [comment]
thx @liadomide for this; I had verified the licesnse prior to merge but didn't think to put them in there.

**Comment by liadomide** [comment]
I see now the relevant comments about the licenses on PR #58 . 
I missed that conversation before.

**Comment by DeLaVlag** [comment]
Thanks for the merge. The title of the readme is not correct. Title should be 'TVB model generation using LEMS format'. Could this be altered?

**Pull request merged**
