### PR TITLE
TVB-2698: Fixed launching simulations with stimuli

### PR DESCRIPTION
**Pull request by VinczeRobert**
I fixed simulation launching with both kinds of stimuli. I went with the assumption that if you have a surface chosen, then only surface stimuli can be chosen, otherwise only region stimuli, based on the code in SimulatorStimulusFragment.

I suggest to merge TVB-2651 first, so I can make a rebase and test each visualizer with these type of surfaces to make sure they are okay.

### CODE REVIEW

**Comment by liadomide** [comment]
I think in the previous version StimuliRegion can be selected both for a region and a surface simulation.
StimuliSurface only in case a surface is selected

**Comment by VinczeRobert** [comment]
> I think in the previous version StimuliRegion can be selected both for a region and a surface simulation.
> StimuliSurface only in case a surface is selected

In that case I think we need a new superclass for the two StimuliIndexes, because currently we have a DataTypeSelectField which can get StimuliRegionIndex or StimuliSurfaceIndex and we would need a way to get both when we have a surface.

**Comment by liadomide** [comment]
I just checked. It does work as I said in TVB 1.5 (both sensor types in case a surface is selected).
We used to have a parent class indeed in that version, for usage on the Simulator field.
`stimulus = patterns.SpatioTemporalPattern( ...)`
The equivalent would be `SpatioTemporalPatternIndex` now.

**Comment by VinczeRobert** [comment]
I made launching with stimuli work as it did in 1.5.6. I have also found out that surface wasn't loading so I fixed that as well.

**Pull request merged**
