### PR TITLE
Add BOLD CUDA driver for RateML

### PR DESCRIPTION
**Pull request by DeLaVlag**
@maedoc here an example of the model and bold cuda driver.

### CODE REVIEW

**Comment by liadomide** [comment]
Hi M. 

> @liadomide two Qs
> 
> * what is merge policy on failing code analysis?

We are still adjusting the Sonar gates, and we have plenty of legacy issues. 
Thus, for now, it is your choice if you take the Sonar failure as blocker, or you ignore it.
Mid term (hopefully this autumn) we should have a more strict and clear policy in place. Feedback on this is welcome.

> * is it ok to start the list of grants in the `ACKNOWLEDGEMENTS.md` file here or we should collect more widely first?

We started a chapter Ackn  at the end of the top README file in the repo: https://github.com/the-virtual-brain/tvb-root#acknowledgments 
This is something that we found in other EBRAINS modules done and given as best practice, but if you have an argument for the separate ACKNOWLEDGEMENTS.md, I have no strong objection to change. 
I would like though to have a unified manner in which all of us add Ack.

**Comment by DeLaVlag** [comment]
Then lets merge it in the acknowledgement section. There no need for a
separate file.

Michiel.

**Comment by liadomide** [comment]
Sorry for messing up your history!
I intended to drop the duplicate acknowledgements (as agreed above). 
Then, I had the not so well inspired idea to do a rebase on your branch against master. While that is ok in general, to put all your commits together, it provoked some unwanted merge conflicts. I trust the final state is good, just the history suffered a little.

As a side note: coverage entirely, while available, is not yet correctly processed by Sonar. We will be working to have that fixed soon.

**Comment by maedoc** [comment]
I didn't have time to review this yet.

**Comment by maedoc** [comment]
Idem, ignore lack of lib testing for the moment, I'm working on it.  hopefully then can review in near future.

**Comment by maedoc** [comment]
I reduced a bit the differences between the standard and bold drivers here, and I think the bold driver could just subclass the standard one.

**Comment by maedoc** [comment]
it seems like the heun file could be completely removed?

**Comment by maedoc** [comment]
as in the other PR just merged, the workflow approach needs improving, otherwise we can merge this.

**Pull request merged**
